2014/07/01 17:06:58 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "findByAttribute".' in E:\xampp\htdocs\Yii\yii14\framework\base\CComponent.php:266
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\db\ar\CActiveRecord.php(227): CComponent->__call('findByAttribute', Array)
#1 E:\xampp\htdocs\Yii\b3805\protected\components\UserIdentity.php(19): CActiveRecord->__call('findByAttribute', Array)
#2 E:\xampp\htdocs\Yii\b3805\protected\components\UserIdentity.php(19): User->findByAttribute(Array)
#3 E:\xampp\htdocs\Yii\b3805\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#4 E:\xampp\htdocs\Yii\yii14\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 E:\xampp\htdocs\Yii\yii14\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 E:\xampp\htdocs\Yii\yii14\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 E:\xampp\htdocs\Yii\b3805\protected\controllers\SiteController.php(84): CModel->validate()
#8 E:\xampp\htdocs\Yii\yii14\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#9 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(130): CFilter->filter(Object(CFilterChain))
#13 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(291): CFilterChain->run()
#14 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(282): CController->run('login')
#16 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#17 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/Yii/b3805/index.php/site/login
HTTP_REFERER=http://localhost/Yii/b3805/index.php/site/login
---
2014/07/01 17:08:07 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "findByAttribute".' in E:\xampp\htdocs\Yii\yii14\framework\base\CComponent.php:266
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\db\ar\CActiveRecord.php(227): CComponent->__call('findByAttribute', Array)
#1 E:\xampp\htdocs\Yii\b3805\protected\components\UserIdentity.php(19): CActiveRecord->__call('findByAttribute', Array)
#2 E:\xampp\htdocs\Yii\b3805\protected\components\UserIdentity.php(19): User->findByAttribute(Array)
#3 E:\xampp\htdocs\Yii\b3805\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#4 E:\xampp\htdocs\Yii\yii14\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 E:\xampp\htdocs\Yii\yii14\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 E:\xampp\htdocs\Yii\yii14\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 E:\xampp\htdocs\Yii\b3805\protected\controllers\SiteController.php(84): CModel->validate()
#8 E:\xampp\htdocs\Yii\yii14\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#9 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(130): CFilter->filter(Object(CFilterChain))
#13 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(291): CFilterChain->run()
#14 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(282): CController->run('login')
#16 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#17 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/Yii/b3805/index.php/site/login
HTTP_REFERER=http://localhost/Yii/b3805/index.php/site/login
---
2014/07/01 17:08:33 [error] [php] Trying to get property of non-object (E:\xampp\htdocs\Yii\b3805\protected\components\UserIdentity.php:22)
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#1 E:\xampp\htdocs\Yii\yii14\framework\base\CModel.php(159): CInlineValidator->validate()
#2 E:\xampp\htdocs\Yii\b3805\protected\controllers\SiteController.php(84): LoginForm->validate()
#3 E:\xampp\htdocs\Yii\yii14\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(133): SiteController->runAction()
#6 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(130): BoosterFilter->filter()
#8 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(291): CFilterChain->run()
#9 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(282): SiteController->run()
#11 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 E:\xampp\htdocs\Yii\b3805\index.php(13): CWebApplication->run()
REQUEST_URI=/Yii/b3805/index.php/site/login
in E:\xampp\htdocs\Yii\b3805\protected\components\UserIdentity.php (22)
in E:\xampp\htdocs\Yii\b3805\protected\models\LoginForm.php (52)
in E:\xampp\htdocs\Yii\b3805\protected\controllers\SiteController.php (84)
2014/07/01 17:10:07 [error] [php] Undefined variable: password (E:\xampp\htdocs\Yii\b3805\protected\components\UserIdentity.php:22)
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#1 E:\xampp\htdocs\Yii\yii14\framework\base\CModel.php(159): CInlineValidator->validate()
#2 E:\xampp\htdocs\Yii\b3805\protected\controllers\SiteController.php(84): LoginForm->validate()
#3 E:\xampp\htdocs\Yii\yii14\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(133): SiteController->runAction()
#6 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(130): BoosterFilter->filter()
#8 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(291): CFilterChain->run()
#9 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(282): SiteController->run()
#11 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 E:\xampp\htdocs\Yii\b3805\index.php(13): CWebApplication->run()
REQUEST_URI=/Yii/b3805/index.php/site/login
in E:\xampp\htdocs\Yii\b3805\protected\components\UserIdentity.php (22)
in E:\xampp\htdocs\Yii\b3805\protected\models\LoginForm.php (52)
in E:\xampp\htdocs\Yii\b3805\protected\controllers\SiteController.php (84)
2014/07/01 17:14:14 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity._id" is not defined.' in E:\xampp\htdocs\Yii\yii14\framework\base\CComponent.php:130
Stack trace:
#0 E:\xampp\htdocs\Yii\b3805\protected\components\UserIdentity.php(30): CComponent->__get('_id')
#1 E:\xampp\htdocs\Yii\yii14\framework\web\auth\CWebUser.php(229): UserIdentity->getId()
#2 E:\xampp\htdocs\Yii\b3805\protected\models\LoginForm.php(71): CWebUser->login(Object(UserIdentity), 0)
#3 E:\xampp\htdocs\Yii\b3805\protected\controllers\SiteController.php(84): LoginForm->login()
#4 E:\xampp\htdocs\Yii\yii14\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#5 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#7 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilter.php(40): CFilterChain->run()
#8 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(130): CFilter->filter(Object(CFilterChain))
#9 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(291): CFilterChain->run()
#10 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(282): CController->run('login')
#12 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/Yii/b3805/index.php/site/login
HTTP_REFERER=http://localhost/Yii/b3805/index.php/site/login
---
2014/07/01 17:17:22 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity._id" is not defined.' in E:\xampp\htdocs\Yii\yii14\framework\base\CComponent.php:173
Stack trace:
#0 E:\xampp\htdocs\Yii\b3805\protected\components\UserIdentity.php(24): CComponent->__set('_id', '1')
#1 E:\xampp\htdocs\Yii\b3805\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 E:\xampp\htdocs\Yii\yii14\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 E:\xampp\htdocs\Yii\yii14\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 E:\xampp\htdocs\Yii\yii14\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 E:\xampp\htdocs\Yii\b3805\protected\controllers\SiteController.php(84): CModel->validate()
#6 E:\xampp\htdocs\Yii\yii14\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(130): CFilter->filter(Object(CFilterChain))
#11 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(291): CFilterChain->run()
#12 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(282): CController->run('login')
#14 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#16 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/Yii/b3805/index.php/site/login
HTTP_REFERER=http://localhost/Yii/b3805/index.php/site/login
---
2014/07/01 17:26:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Expenditure".' in E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('Expenditure')
#1 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Yii/b3805/index.php/Expenditure
HTTP_REFERER=http://localhost/Yii/b3805/index.php/gii/crud/index
---
2014/07/01 17:28:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Expenditure".' in E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('Expenditure')
#1 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Yii/b3805/index.php/Expenditure
HTTP_REFERER=http://localhost/Yii/b3805/index.php/gii/crud/index
---
2014/07/01 17:28:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Expenditure".' in E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('Expenditure')
#1 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Yii/b3805/index.php/Expenditure
HTTP_REFERER=http://localhost/Yii/b3805/index.php/gii/crud/index
---
2014/07/01 17:28:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Expenditure".' in E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('Expenditure')
#1 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Yii/b3805/index.php/Expenditure
HTTP_REFERER=http://localhost/Yii/b3805/index.php/gii/crud/index
---
2014/07/01 17:30:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "expenditure".' in E:\xampp\htdocs\Yii\yii14\framework\web\CController.php:483
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(270): CController->missingAction('expenditure')
#1 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(282): CController->run('expenditure')
#2 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('expenditure/exp...')
#3 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/b3805/index.php/expenditure/expenditure
---
2014/07/01 17:31:36 [error] [exception.CException] exception 'CException' with message 'Alias "Expenditure.models.*" is invalid. Make sure it points to an existing directory or file.' in E:\xampp\htdocs\Yii\yii14\framework\YiiBase.php:347
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\base\CModule.php(226): YiiBase::import('Expenditure.mod...')
#1 E:\xampp\htdocs\Yii\b3805\protected\modules\expenditure\ExpenditureModule.php(13): CModule->setImport(Array)
#2 E:\xampp\htdocs\Yii\yii14\framework\base\CModule.php(90): ExpenditureModule->init()
#3 E:\xampp\htdocs\Yii\yii14\framework\YiiBase.php(206): CModule->__construct('expenditure', NULL, Array)
#4 E:\xampp\htdocs\Yii\yii14\framework\base\CModule.php(282): YiiBase::createComponent('expenditure.Exp...', 'expenditure', NULL, Array)
#5 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(337): CModule->getModule('expenditure')
#6 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(276): CWebApplication->createController('expenditure')
#7 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('expenditure')
#8 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/Yii/b3805/index.php/expenditure/
---
2014/07/01 17:31:51 [error] [exception.CException] exception 'CException' with message 'Alias "Expenditure.models.*" is invalid. Make sure it points to an existing directory or file.' in E:\xampp\htdocs\Yii\yii14\framework\YiiBase.php:347
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\base\CModule.php(226): YiiBase::import('Expenditure.mod...')
#1 E:\xampp\htdocs\Yii\b3805\protected\modules\expenditure\ExpenditureModule.php(13): CModule->setImport(Array)
#2 E:\xampp\htdocs\Yii\yii14\framework\base\CModule.php(90): ExpenditureModule->init()
#3 E:\xampp\htdocs\Yii\yii14\framework\YiiBase.php(206): CModule->__construct('expenditure', NULL, Array)
#4 E:\xampp\htdocs\Yii\yii14\framework\base\CModule.php(282): YiiBase::createComponent('expenditure.Exp...', 'expenditure', NULL, Array)
#5 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(337): CModule->getModule('expenditure')
#6 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(276): CWebApplication->createController('expenditure')
#7 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('expenditure')
#8 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/Yii/b3805/index.php/expenditure/
---
2014/07/01 17:32:36 [error] [exception.CException] exception 'CException' with message 'Alias "Expenditure.models.*" is invalid. Make sure it points to an existing directory or file.' in E:\xampp\htdocs\Yii\yii14\framework\YiiBase.php:347
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\base\CModule.php(226): YiiBase::import('Expenditure.mod...')
#1 E:\xampp\htdocs\Yii\b3805\protected\modules\expenditure\ExpenditureModule.php(13): CModule->setImport(Array)
#2 E:\xampp\htdocs\Yii\yii14\framework\base\CModule.php(90): ExpenditureModule->init()
#3 E:\xampp\htdocs\Yii\yii14\framework\YiiBase.php(206): CModule->__construct('expenditure', NULL, Array)
#4 E:\xampp\htdocs\Yii\yii14\framework\base\CModule.php(282): YiiBase::createComponent('expenditure.Exp...', 'expenditure', NULL, Array)
#5 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(337): CModule->getModule('expenditure')
#6 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(276): CWebApplication->createController('expenditure')
#7 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('expenditure')
#8 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/Yii/b3805/index.php/expenditure/
---
2014/07/01 17:32:37 [error] [exception.CException] exception 'CException' with message 'Alias "Expenditure.models.*" is invalid. Make sure it points to an existing directory or file.' in E:\xampp\htdocs\Yii\yii14\framework\YiiBase.php:347
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\base\CModule.php(226): YiiBase::import('Expenditure.mod...')
#1 E:\xampp\htdocs\Yii\b3805\protected\modules\expenditure\ExpenditureModule.php(13): CModule->setImport(Array)
#2 E:\xampp\htdocs\Yii\yii14\framework\base\CModule.php(90): ExpenditureModule->init()
#3 E:\xampp\htdocs\Yii\yii14\framework\YiiBase.php(206): CModule->__construct('expenditure', NULL, Array)
#4 E:\xampp\htdocs\Yii\yii14\framework\base\CModule.php(282): YiiBase::createComponent('expenditure.Exp...', 'expenditure', NULL, Array)
#5 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(337): CModule->getModule('expenditure')
#6 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(276): CWebApplication->createController('expenditure')
#7 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('expenditure')
#8 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/Yii/b3805/index.php/expenditure/
---
2014/07/01 17:39:18 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1. The SQL statement executed was: SELECT COUNT(*) FROM `expenditure` `t` WHERE user_id = :user).
in E:\xampp\htdocs\Yii\b3805\protected\modules\expenditure\views\expenditure\index.php (20)
in E:\xampp\htdocs\Yii\b3805\protected\modules\expenditure\controllers\ExpenditureController.php (113)
in E:\xampp\htdocs\Yii\b3805\index.php (13)
2014/07/01 17:39:18 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1. The SQL statement executed was: SELECT COUNT(*) FROM `expenditure` `t` WHERE user_id = :user)' in E:\xampp\htdocs\Yii\yii14\framework\db\CDbCommand.php:543
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\db\CDbCommand.php(433): CDbCommand->queryInternal('fetchColumn', 0, Array)
#1 E:\xampp\htdocs\Yii\yii14\framework\db\ar\CActiveRecord.php(1601): CDbCommand->queryScalar()
#2 E:\xampp\htdocs\Yii\yii14\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#3 E:\xampp\htdocs\Yii\yii14\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#4 E:\xampp\htdocs\Yii\yii14\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#5 E:\xampp\htdocs\Yii\yii14\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#6 E:\xampp\htdocs\Yii\yii14\framework\zii\widgets\CBaseListView.php(111): CDataProvider->getData()
#7 E:\xampp\htdocs\Yii\yii14\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#8 E:\xampp\htdocs\Yii\yii14\framework\web\CBaseController.php(147): CListView->init()
#9 E:\xampp\htdocs\Yii\yii14\framework\web\CBaseController.php(172): CBaseController->createWidget('zii.widgets.CLi...', Array)
#10 E:\xampp\htdocs\Yii\b3805\protected\modules\expenditure\views\expenditure\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#11 E:\xampp\htdocs\Yii\yii14\framework\web\CBaseController.php(126): require('E:\xampp\htdocs...')
#12 E:\xampp\htdocs\Yii\yii14\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\xampp\htdocs...', Array, true)
#13 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(869): CBaseController->renderFile('E:\xampp\htdocs...', Array, true)
#14 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#15 E:\xampp\htdocs\Yii\b3805\protected\modules\expenditure\controllers\ExpenditureController.php(113): CController->render('index', Array)
#16 E:\xampp\htdocs\Yii\yii14\framework\web\actions\CInlineAction.php(49): ExpenditureController->actionIndex()
#17 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#19 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(130): CFilter->filter(Object(CFilterChain))
#21 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilter.php(40): CFilterChain->run()
#22 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#23 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#24 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#25 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(291): CFilterChain->run()
#26 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#27 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(282): CController->run('')
#28 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('expenditure')
#29 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#30 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#31 {main}
REQUEST_URI=/Yii/b3805/index.php/expenditure/
---
2014/07/01 17:39:52 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in E:\xampp\htdocs\Yii\yii14\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(291): CFilterChain->run()
#6 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(282): CController->run('admin')
#8 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('expenditure/exp...')
#9 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/Yii/b3805/index.php/expenditure/expenditure/admin
HTTP_REFERER=http://localhost/Yii/b3805/index.php/expenditure/
---
2014/07/02 16:29:57 [error] [exception.CException] exception 'CException' with message 'Alias "booster.filters.BoosterFilter" is invalid. Make sure it points to an existing PHP file and the file is readable.' in E:\xampp\htdocs\Yii\yii14\framework\YiiBase.php:322
Stack trace:
#0 E:\xampp\htdocs\Yii\yii14\framework\YiiBase.php(196): YiiBase::import('booster.filters...', true)
#1 E:\xampp\htdocs\Yii\yii14\framework\web\filters\CFilterChain.php(89): YiiBase::createComponent(Array)
#2 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(291): CFilterChain::create(Object(SiteController), Object(CInlineAction), Array)
#3 E:\xampp\htdocs\Yii\yii14\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(282): CController->run('login')
#5 E:\xampp\htdocs\Yii\yii14\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#6 E:\xampp\htdocs\Yii\yii14\framework\base\CApplication.php(180): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii\b3805\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/Yii/b3805/index.php/site/login
---
